"""empty message

Revision ID: 22855be0e971
Revises: 0763d677d453
Create Date: 2026-08-19 17:27:16.896302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22855be0e971'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colegios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email_contacto', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('activities_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('ID_Activity', sa.String(length=100), nullable=False),
    sa.Column('Event_Name', sa.String(length=255), nullable=True),
    sa.Column('Responsable_ID', sa.String(length=100), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('Semaforo', sa.String(length=50), nullable=True),
    sa.Column('Form_Status', sa.String(length=50), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Progress_Precent', sa.String(length=50), nullable=True),
    sa.Column('Deadline', sa.String(length=50), nullable=True),
    sa.Column('Final_Grade', sa.String(length=50), nullable=True),
    sa.Column('Admin_Feedback', sa.Text(), nullable=True),
    sa.Column('Start', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_details_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('ID_Detail', sa.String(length=100), nullable=False),
    sa.Column('ID_Activity', sa.String(length=100), nullable=True),
    sa.Column('Academic_Objective', sa.Text(), nullable=True),
    sa.Column('Target_Vocabulary', sa.Text(), nullable=True),
    sa.Column('Language_Structures', sa.Text(), nullable=True),
    sa.Column('Speaking_Challenge', sa.Text(), nullable=True),
    sa.Column('Interactive_Stages', sa.Text(), nullable=True),
    sa.Column('Resource_Links', sa.String(length=255), nullable=True),
    sa.Column('Evaluation_Method', sa.String(length=100), nullable=True),
    sa.Column('Evidence_Preview', sa.String(length=255), nullable=True),
    sa.Column('Budget_Status', sa.String(length=50), nullable=True),
    sa.Column('Last_Updated', sa.String(length=50), nullable=True),
    sa.Column('Feedback_Score', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('ID_Lesson_Ref', sa.String(length=100), nullable=False),
    sa.Column('Timing_Control', sa.String(length=100), nullable=True),
    sa.Column('The_Hook_Check', sa.String(length=100), nullable=True),
    sa.Column('Vocabulary_Focus', sa.String(length=100), nullable=True),
    sa.Column('Scaffolding_Check', sa.String(length=100), nullable=True),
    sa.Column('Student_Talk_Time', sa.String(length=100), nullable=True),
    sa.Column('Thinking_Routine', sa.String(length=100), nullable=True),
    sa.Column('Resource_Sync', sa.String(length=100), nullable=True),
    sa.Column('Discipline_Flow', sa.String(length=100), nullable=True),
    sa.Column('Goal_Achievement', sa.String(length=100), nullable=True),
    sa.Column('Audio_Video_URL', sa.String(length=255), nullable=True),
    sa.Column('Feedback', sa.Text(), nullable=True),
    sa.Column('Teacher', sa.String(length=100), nullable=True),
    sa.Column('Grade', sa.String(length=100), nullable=True),
    sa.Column('Score', sa.String(length=50), nullable=True),
    sa.Column('Areas_for_Improvement', sa.Text(), nullable=True),
    sa.Column('Next_Steps', sa.Text(), nullable=True),
    sa.Column('Commitment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculum_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('ID_Map', sa.String(length=100), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Subject', sa.String(length=100), nullable=True),
    sa.Column('Grade', sa.String(length=100), nullable=True),
    sa.Column('Term', sa.String(length=50), nullable=True),
    sa.Column('Content_JSON', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_planners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('ID_Setup', sa.String(length=100), nullable=False),
    sa.Column('Grade', sa.String(length=100), nullable=True),
    sa.Column('Subject', sa.String(length=100), nullable=True),
    sa.Column('Start_Date', sa.String(length=50), nullable=True),
    sa.Column('Finish_Date', sa.String(length=50), nullable=True),
    sa.Column('Term', sa.String(length=50), nullable=True),
    sa.Column('Session_Number', sa.String(length=50), nullable=True),
    sa.Column('Topic', sa.String(length=255), nullable=True),
    sa.Column('Objective', sa.Text(), nullable=True),
    sa.Column('The_Hook', sa.Text(), nullable=True),
    sa.Column('Vocabulary', sa.Text(), nullable=True),
    sa.Column('Big_5', sa.String(length=100), nullable=True),
    sa.Column('Thinking_Skill', sa.String(length=100), nullable=True),
    sa.Column('Language_Frame', sa.Text(), nullable=True),
    sa.Column('Thinking_Routine', sa.String(length=100), nullable=True),
    sa.Column('Richmond_Resources', sa.String(length=255), nullable=True),
    sa.Column('Activity_Link', sa.String(length=255), nullable=True),
    sa.Column('Parent_Task', sa.Text(), nullable=True),
    sa.Column('Weekly_Challenge', sa.Text(), nullable=True),
    sa.Column('Percent_Status', sa.String(length=50), nullable=True),
    sa.Column('TeacherSource', sa.String(length=100), nullable=True),
    sa.Column('AI_Content_JSON', sa.Text(), nullable=True),
    sa.Column('ClassDojo_Link', sa.String(length=255), nullable=True),
    sa.Column('Interactive_Feedback', sa.Text(), nullable=True),
    sa.Column('Feedback_Questions_JSON', sa.Text(), nullable=True),
    sa.Column('DBA_Reference', sa.String(length=255), nullable=True),
    sa.Column('SDG_Connection', sa.String(length=255), nullable=True),
    sa.Column('Assessment_Dimension', sa.String(length=100), nullable=True),
    sa.Column('Evaluation_Instrument', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('Fecha', sa.String(length=50), nullable=True),
    sa.Column('Proveedor', sa.String(length=100), nullable=True),
    sa.Column('Mensaje', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lumi_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('Teacher_Key', sa.String(length=100), nullable=False),
    sa.Column('Avatar_Style', sa.String(length=100), nullable=True),
    sa.Column('Avatar_Seed', sa.String(length=100), nullable=True),
    sa.Column('Avatar_Options_JSON', sa.Text(), nullable=True),
    sa.Column('Lumi_Name', sa.String(length=100), nullable=True),
    sa.Column('Last_Updated', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neuro_stimulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('ID_Neuro', sa.String(length=100), nullable=False),
    sa.Column('Grade', sa.String(length=100), nullable=True),
    sa.Column('Term', sa.String(length=50), nullable=True),
    sa.Column('Week_Number', sa.String(length=50), nullable=True),
    sa.Column('Day_of_Week', sa.String(length=50), nullable=True),
    sa.Column('Target_Skill', sa.String(length=100), nullable=True),
    sa.Column('Language', sa.String(length=50), nullable=True),
    sa.Column('Activity_Type', sa.String(length=100), nullable=True),
    sa.Column('Title_Activity', sa.String(length=255), nullable=True),
    sa.Column('Instruction_Text', sa.Text(), nullable=True),
    sa.Column('Resource_Link', sa.String(length=255), nullable=True),
    sa.Column('Extra_Data_JSON', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('ID_Meeting', sa.String(length=100), nullable=False),
    sa.Column('ID_Student', sa.String(length=100), nullable=True),
    sa.Column('Student_Name', sa.String(length=255), nullable=True),
    sa.Column('Grade', sa.String(length=100), nullable=True),
    sa.Column('Meeting_Reason', sa.String(length=255), nullable=True),
    sa.Column('Meeting_Date', sa.String(length=50), nullable=True),
    sa.Column('Attended', sa.String(length=50), nullable=True),
    sa.Column('Commitment_Signed', sa.String(length=50), nullable=True),
    sa.Column('Commitments', sa.Text(), nullable=True),
    sa.Column('Next_Followup', sa.String(length=50), nullable=True),
    sa.Column('Responsible', sa.String(length=100), nullable=True),
    sa.Column('Term', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prime_math',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('ID_Map', sa.String(length=100), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Subject', sa.String(length=100), nullable=True),
    sa.Column('Grade', sa.String(length=100), nullable=True),
    sa.Column('Term', sa.String(length=50), nullable=True),
    sa.Column('Content_JSON', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('ID_Student', sa.String(length=100), nullable=False),
    sa.Column('Student_Name', sa.String(length=255), nullable=False),
    sa.Column('Grade', sa.String(length=100), nullable=True),
    sa.Column('Entry_Date', sa.String(length=50), nullable=True),
    sa.Column('Expected_MCER', sa.String(length=50), nullable=True),
    sa.Column('Diagnostic_Result', sa.String(length=100), nullable=True),
    sa.Column('Entry_Test_Richmond', sa.String(length=100), nullable=True),
    sa.Column('Assignments', sa.String(length=100), nullable=True),
    sa.Column('Observations', sa.Text(), nullable=True),
    sa.Column('Verdict', sa.String(length=100), nullable=True),
    sa.Column('Term', sa.String(length=50), nullable=True),
    sa.Column('Teacher_Key', sa.String(length=100), nullable=True),
    sa.Column('Created_By', sa.String(length=100), nullable=True),
    sa.Column('Last_Updated', sa.String(length=50), nullable=True),
    sa.Column('Active', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syllabus_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('ID_Syllabus', sa.String(length=100), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Subject', sa.String(length=100), nullable=True),
    sa.Column('Grade', sa.String(length=100), nullable=True),
    sa.Column('Summary_JSON', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('ID_Notification', sa.String(length=100), nullable=False),
    sa.Column('Target_User_Key', sa.String(length=100), nullable=True),
    sa.Column('Target_Teacher_Name', sa.String(length=255), nullable=True),
    sa.Column('Message', sa.Text(), nullable=True),
    sa.Column('Sender', sa.String(length=100), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('Created_At', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('User_Key', sa.String(length=100), nullable=False),
    sa.Column('Teacher_Name', sa.String(length=255), nullable=False),
    sa.Column('Assigned_Grade', sa.String(length=100), nullable=True),
    sa.Column('Assigned_Subject', sa.String(length=100), nullable=True),
    sa.Column('Total_Lessons', sa.Integer(), nullable=True),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('ROL', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('weekly_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('ID_Challenge', sa.String(length=100), nullable=False),
    sa.Column('Teacher_Key', sa.String(length=100), nullable=True),
    sa.Column('Challenge_Description', sa.Text(), nullable=True),
    sa.Column('Start_Date', sa.String(length=50), nullable=True),
    sa.Column('Days_Active', sa.String(length=50), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('Evidence_Note', sa.Text(), nullable=True),
    sa.Column('Bilingual_Resources', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('weekly_challenges')
    op.drop_table('users')
    op.drop_table('teachers_users')
    op.drop_table('teacher_notifications')
    op.drop_table('syllabus_templates')
    op.drop_table('students_alert')
    op.drop_table('prime_math')
    op.drop_table('parent_meetings')
    op.drop_table('neuro_stimulation')
    op.drop_table('lumi_config')
    op.drop_table('logs_ia')
    op.drop_table('lesson_planners')
    op.drop_table('curriculum_maps')
    op.drop_table('class_observations')
    op.drop_table('activity_details_form')
    op.drop_table('activities_calendar')
    op.drop_table('colegios')
    # ### end Alembic commands ###
