"""empty message

Revision ID: 5781e2e955f6
Revises: 22855be0e971
Create Date: 2026-08-19 20:27:45.250833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5781e2e955f6'
down_revision = '22855be0e971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_details_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Score', sa.String(length=50), nullable=True))
        batch_op.alter_column('Resource_Links',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('class_observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Teacher_Name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('Subject', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('Global_Score', sa.String(length=50), nullable=True))

    with op.batch_alter_table('lesson_planners', schema=None) as batch_op:
        batch_op.alter_column('Big_5',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('Thinking_Skill',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('Activity_Link',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('students_alert', schema=None) as batch_op:
        batch_op.alter_column('Assignments',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('weekly_challenges', schema=None) as batch_op:
        batch_op.alter_column('Bilingual_Resources',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_challenges', schema=None) as batch_op:
        batch_op.alter_column('Bilingual_Resources',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('students_alert', schema=None) as batch_op:
        batch_op.alter_column('Assignments',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('lesson_planners', schema=None) as batch_op:
        batch_op.alter_column('Activity_Link',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('Thinking_Skill',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('Big_5',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('class_observations', schema=None) as batch_op:
        batch_op.drop_column('Global_Score')
        batch_op.drop_column('Subject')
        batch_op.drop_column('Teacher_Name')

    with op.batch_alter_table('activity_details_form', schema=None) as batch_op:
        batch_op.alter_column('Resource_Links',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('Score')
        batch_op.drop_column('Feedback')

    # ### end Alembic commands ###
