"""empty message

Revision ID: 6f8ea32052cc
Revises: 906a69bfe3fb
Create Date: 2026-09-15 16:35:48.095574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f8ea32052cc'
down_revision = '906a69bfe3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students_alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Subject', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students_alert', schema=None) as batch_op:
        batch_op.drop_column('Subject')

    # ### end Alembic commands ###
