"""empty message

Revision ID: 906a69bfe3fb
Revises: 833506a61901
Create Date: 2026-08-20 17:34:43.403668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906a69bfe3fb'
down_revision = '833506a61901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_planners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Teacher', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('Source', sa.String(length=100), nullable=True))
        batch_op.drop_column('Vocabulary')
        batch_op.drop_column('TeacherSource')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_planners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TeacherSource', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Vocabulary', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('Source')
        batch_op.drop_column('Teacher')

    # ### end Alembic commands ###
